---
AWSTemplateFormatVersion: 2010-09-09

Description: Arquitectura de referencia para SIU Guarani - Creacion de CloudFront distribution

Metadata:

  Authors:
    Description: Marcos Boaglio (mboaglio@amazon.com)
  License:
    Description: 'Copyright 2020 Amazon.com, Inc. and its affiliates. All Rights Reserved.
                  SPDX-License-Identifier: MIT-0'

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: AWS Parameters
      Parameters:
        - CloudFrontAcmCertificate
        - SIUDomainName
        - PublicAlbDnsName
    ParameterLabels:
      CloudFrontAcmCertificate:
        default: ARN del Certificado de CloudFront
      PublicAlbDnsName:
        default: Nombre publico del DNS del ELB
      SIUDomainName:
        default: Dominio del sitio

Parameters:

  CloudFrontAcmCertificate:
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: '[ Opcional ] El ARN del certificado AWS Certification Manager para la distribucion de CloudFront - este certificado deberia crearse en us-east-1 (N. Virginia) y deberia referenciar el dominio del campo de abajo.'
    Type: String
  PublicAlbDnsName:
    Description: Nombre publico del DNS del ELB.
    Type: String
  SIUDomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Opcional ] Nombre del dominio del sitio (e.g. siu.universidad.edu.ar).'
    Type: String

Conditions:

  SslCertificate:
    !Not [ !Equals [ '', !Ref CloudFrontAcmCertificate ] ]
  NoSslCertificate:
    !Equals [ '', !Ref CloudFrontAcmCertificate ]
  SIUDomainName:
    !Not [ !Equals [ '', !Ref SIUDomainName ] ]
  NoSIUDomainName:
    !Equals [ '', !Ref SIUDomainName ]

Resources:

  CloudFrontDistributionNoSslCertificate:
    Type: AWS::CloudFront::Distribution
    Condition: NoSslCertificate
    Properties:
      DistributionConfig:
        Aliases:
        - !If [ SIUDomainName, !Join [ '', [ '*.', !Ref SIUDomainName ] ], !Ref 'AWS::NoValue' ]
        CacheBehaviors:
        - PathPattern: wp-includes/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - Host
          TargetOriginId: elb
          ViewerProtocolPolicy: allow-all
          Compress: true
        - PathPattern: wp-content/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - Host
          TargetOriginId: elb
          ViewerProtocolPolicy: allow-all
          Compress: true
        Comment: !Ref 'AWS::StackName'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
            - '*'
            Cookies:
              Forward: all
          TargetOriginId: elb
          ViewerProtocolPolicy: allow-all
          Compress: true
        Enabled: true
        Origins:
        - DomainName: !Ref PublicAlbDnsName
          Id: elb
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
  CloudFrontDistributionSslCertificate:
    Type: AWS::CloudFront::Distribution
    Condition: SslCertificate
    Properties:
      DistributionConfig:
        Aliases:
        - !If [ SIUDomainName, !Join [ '', [ '*.', !Ref SIUDomainName ] ], !Ref 'AWS::NoValue' ]
        CacheBehaviors:
        - PathPattern: wp-includes/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - Host
          TargetOriginId: elb
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        - PathPattern: wp-content/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - Host
          TargetOriginId: elb
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        Comment: !Ref 'AWS::StackName'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
            - '*'
            Cookies:
              Forward: all
          TargetOriginId: elb
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        Enabled: true
        Origins:
        - DomainName: !Ref PublicAlbDnsName
          Id: elb
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

Outputs:

  DnsEndpoint:
    Value: !If [ NoSslCertificate, !GetAtt CloudFrontDistributionNoSslCertificate.DomainName, !GetAtt CloudFrontDistributionSslCertificate.DomainName ]
  DnsHostname:
    Value: !If [ NoSslCertificate, !Join [ '', [ 'http://', !GetAtt CloudFrontDistributionNoSslCertificate.DomainName ] ], !Join [ '', [ 'https://', !GetAtt CloudFrontDistributionSslCertificate.DomainName ] ] ]
